### PR TITLE
rename-provided-to-implementation-dependencies

### PR DESCRIPTION
**Pull request by nicolasdevienne**

### CODE REVIEW

**Comment by anttivuor** [comment]
Thanks @nicolasdevienne! Merging this 👍

**Comment by nicolasdevienne** [comment]
> Thanks @nicolasdevienne! Merging this 👍

Thx @anttivuor! When I execute command `yarn add react-native-switch-audio-output-android`, I have always the previous version. Can you update it please?

**Comment by anttivuor** [comment]
Yeah, forgot to update the package to NPM. It should now be available

**Comment by nicolasdevienne** [comment]
> Yeah, forgot to update the package to NPM. It should now be available

You're the best! :)

**Pull request merged**
